### ISSUE TITLE
Upload-only mode?

### ISSUE THREAD

**Issue by nomeata** [derekelkins/sws#12]
I want to receive a file into a directory with other files that I don't want the user to see. Have you considered an upload-only mode? Maybe with a more minimalistic, more user-friendly HTML interface?

**Comment by derekelkins** [comment]
I hadn't considered that, but that's not a bad idea. I'll probably implement a stab at it in the next few days. I'll have to decide what I want to happen if two files with the same name are uploaded. I'm leaning toward disallowing overwriting to avoid files being unwittingly overwritten. This would leak the existence of such files though. I may make it an option. Another point in the design space would be auto-generating non-conflicting names, e.g. adding a `.1`, `.2`, etc. or some similar scheme.

**Comment by nomeata** [comment]
Generating fresh names seems like a good solution.

**Comment by derekelkins** [comment]
I've uploaded a new version. By default it will give an error when attempting to overwrite a file (both in the upload-only and the read/write mode). The `--overwrite` option allows changing this behavior to also allow overwriting or to write to generate a new name. I may make the generated upload page look nicer instead of just being a raw upload control. (If nothing else, I should probably at least center it...)
